<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import type { ExamConfig } from '@/types/exam';

const props = defineProps<{
  config: ExamConfig;
}>();

// --- 这里配置不需要用户修改的固定文案 ---
const FIXED_CONFIG = {
  exportHeaderSub: '—— 凉宫春日应援团 · 让世界变得更加热闹的考试委员会 ——',
  exportOrgName: '凉宫春日应援团 · 让世界变得更加热闹的考试委员会',
  exportFooterText: 'Generated by Haruyuki.cn',
  qrCodeText: '扫码挑战'
};

// 交互状态追踪：记录哪些输入框被用户"摸过"(blur)
const touched = reactive<Record<string, boolean>>({
  title: false,
  paperTitle: false,
  paperSubtitle: false,
  paperMeta: false,
  author: false,
  contact: false,
  className: false
});

// 是否显示所有错误（用于点击提交时的强制校验）
const showAllErrors = ref(false);

// 组件加载时，强制覆盖这些配置项
onMounted(() => {
  Object.assign(props.config, FIXED_CONFIG);
});

// 标记字段为已触碰
const handleBlur = (field: string) => {
  touched[field] = true;
};

// 判断是否应该显示错误红框
// 规则：(显示所有错误 OR 用户摸过该字段) AND 字段值为空
const isError = (field: keyof ExamConfig) => {
  // @ts-ignore
  return (showAllErrors.value || touched[field as string]) && !props.config[field];
};

// 暴露给父组件的校验方法
const validate = () => {
  showAllErrors.value = true; // 强制显示所有错误
  const requiredFields = ['title', 'paperTitle', 'paperSubtitle', 'paperMeta', 'author', 'contact', 'className'];
  // 返回是否所有字段都有值
  // @ts-ignore
  return requiredFields.every(f => !!props.config[f as keyof ExamConfig]);
};

defineExpose({ validate });
</script>

<template>
  <div class="panel" style="margin-bottom: 20px;">
    <h3>📄 界面预览</h3>
    <div class="preview-container">
      <div class="grid">
        <div class="card">
          <div class="tag user" :value="config.author">{{config.author || "创作者署名"}}</div>
          <h2 :value="config.title">{{ config.title ||"试卷名称"}}</h2>
          <p :value="config.paperSubtitle">{{ config.paperSubtitle ||"试卷描述"}}</p>
          <div class="meta">包含n道题目</div>
        </div>
      </div>
      <div class="grid">
        <!-- 试卷卷头预览 -->
        <div class="paper-preview">
          <div class="paper-preview-header">
            <div class="preview-h1">{{ config.paperTitle || "卷头标题" }}</div>
            <div class="preview-h2">{{ config.paperMeta || "辅助文本" }}</div>
            <div class="preview-fields">
              <div class="preview-field">
                <span>姓名</span>
                <div class="preview-line">
                  <span class="preview-handname">示例姓名</span>
                </div>
              </div>
              <div class="preview-field">
                <span>考号</span>
                <div class="preview-line">
                  <span class="preview-handmeta">20240203001</span>
                </div>
              </div>
              <div class="preview-field">
                <span>班级</span>
                <div class="preview-line">
                  <span class="preview-handmeta">{{ config.className || "班级名称" }}</span>
                </div>
              </div>
              <div class="preview-field">
                <span>日期</span>
                <div class="preview-line">
                  <span class="preview-handmeta">2024年2月3日</span>
                </div>
              </div>
            </div>
          </div>
          <div class="preview-note">试卷卷头的预览效果</div>
        </div>
      </div>
    </div>
  </div>
  <div class="panel">
    <!-- 第一部分：试卷基础信息 -->
    <h3>📄 试卷基础信息</h3>
    
    <div class="form-group">
      <label>
        试卷名称 <span class="required">*</span>
        <span class="tip">浏览器标签页显示的标题，以及首页试卷列表显示的名称。</span>
      </label>
      <input 
        v-model="config.title" 
        type="text" 
        placeholder="例如：SOS团入团测试"
        :class="{ error: isError('title') }"
        @blur="handleBlur('title')"
      />
    </div>

    <div class="row">
      <div class="form-group half">
        <label>
          卷头标题 <span class="required">*</span>
          <span class="tip">印在试卷上的标题字。</span>
        </label>
        <input 
          v-model="config.paperTitle" 
          type="text" 
          placeholder="例如：SOS团第15532次期末考试"
          :class="{ error: isError('paperTitle') }"
          @blur="handleBlur('paperTitle')"
        />
      </div>
      <div class="form-group half">
        <label>
          试卷描述 <span class="required">*</span>
          <span class="tip">显示在首页试卷列表的标题下方。</span>
        </label>
        <input 
          v-model="config.paperSubtitle" 
          type="text" 
          placeholder="例如：测试你是否具有成为团员的资格！"
          :class="{ error: isError('paperSubtitle') }"
          @blur="handleBlur('paperSubtitle')"
        />
      </div>
    </div>

    <div class="form-group">
      <label>
        班级名称 <span class="required">*</span>
        <span class="tip">对应试卷信息栏中的班级名。</span>
      </label>
      <input 
        v-model="config.className" 
        type="text" 
        placeholder=""
        :class="{ error: isError('className') }"
        @blur="handleBlur('className')"
      />
    </div>

    <div class="form-group">
      <label>
        辅助文本 <span class="required">*</span>
        <span class="tip">显示在卷头标题的下方，可以放补充信息或拟真文案。</span>
      </label>
      <input 
        v-model="config.paperMeta" 
        type="text" 
        placeholder="例如：绝密 ★ 启用前"
        :class="{ error: isError('paperMeta') }"
        @blur="handleBlur('paperMeta')"
      />
    </div>

    <!-- 第二部分：创建者信息 -->
    <h3>👤 创建者信息</h3>

    <div class="row">
      <div class="form-group half">
        <label>
          创建者署名 <span class="required">*</span>
          <span class="tip">显示在首页卡片右上角。</span>
        </label>
        <input 
          v-model="config.author" 
          type="text" 
          placeholder=""
          :class="{ error: isError('author') }"
          @blur="handleBlur('author')"
        />
      </div>
      <div class="form-group half">
        <label>
          联系方式 (QQ/邮箱) <span class="required">*</span>
          <span class="tip">仅管理员可见。</span>
        </label>
        <input 
          v-model="config.contact" 
          type="text" 
          placeholder=""
          :class="{ error: isError('contact') }"
          @blur="handleBlur('contact')"
        />
      </div>
    </div>
    
  </div>
</template>

<style scoped>
.panel { padding: 20px; background: #fff; border-radius: 12px; box-shadow: 0 2px 12px rgba(0,0,0,0.04); }
h3 { margin: 32px 0 16px 0; font-size: 18px; color: #1a1c20; border-left: 4px solid #16a34a; padding-left: 10px; }
h3:first-child { margin-top: 0; }
.form-group { margin-bottom: 16px; }
.row { display: flex; gap: 20px; }
.half { flex: 1; }
label { display: block; font-weight: 700; font-size: 14px; margin-bottom: 6px; color: #374151; }
.tip { display: block; font-weight: 400; font-size: 12px; color: #9ca3af; margin-top: 2px; }
.required { color: #ef4444; margin-left: 2px; }

/* 预览容器：桌面端横向排列，移动端纵向排列 */
.preview-container {
  display: flex;
  gap: 24px;
  align-items: flex-start;
}

.grid {
  display: grid;
  grid-template-columns: 1fr; /* 单列布局，让卡片占据全部宽度 */
  gap: 24px;
  flex: 1;
  min-width: 0; /* 防止 flex 子元素溢出 */
}
.card {
  /* 卡片背景保持不透明，确保内容清晰 */
  background: rgba(255, 255, 255, 0.95); /* 更不透明一些，增强文字对比 */
  backdrop-filter: blur(10px); 
  border-radius: 20px; /* 圆角加大 */
  padding: 28px; /* 内边距加大 */
  box-shadow: 0 4px 20px rgba(0,0,0,0.08);
  cursor: pointer;
  transition: transform 0.2s, box-shadow 0.2s, border-color 0.2s;
  position: relative;
  overflow: hidden;
  border: 2px solid rgba(255,255,255,0.8);
  width: 100%; /* 占据 grid 的全部宽度 */
  max-width: 500px; /* 限制最大宽度 */
}
.card .tag {
  position: absolute;
  top: 20px;
  right: 20px;
  font-size: 11px;
  font-weight: 900;
  padding: 6px 10px;
  border-radius: 8px;
  text-transform: uppercase;
}
.card .tag.user { background: #f3f4f6; color: #4b5563;  }
.card h2 {  
  margin: 0 80px 10px 0; 
  font-size: 22px; 
  font-weight: 800; 
  color: #000; 
  line-height: 1.3;
  word-wrap: break-word;
  overflow: visible; /* 允许文字完整显示 */
  text-overflow: clip; /* 不显示省略号 */
}
.card p {  margin: 0 0 20px 0; font-size: 16px; font-weight: 500; color: #374151; line-height: 1.6; }
.card .meta { font-size: 13px; color: #6b7280; font-weight: 700; }

input[type="text"] {width: 100%; padding: 10px 12px; border: 1px solid #e5e7eb; border-radius: 8px; font-size: 14px; transition: all 0.2s;}
input[type="text"]:focus { border-color: #16a34a; outline: none; box-shadow: 0 0 0 3px rgba(22, 163, 74, 0.1); }
input[type="text"].error { border-color: #ef4444; background-color: #fef2f2; }
input[type="text"].error:focus { box-shadow: 0 0 0 3px rgba(239, 68, 68, 0.1); }

/* 试卷卷头预览样式 */
.paper-preview {
  background: #f7f4ec;
  border-radius: 12px;
  padding: 20px;
  border: 1px solid rgba(0, 0, 0, 0.1);
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
  position: relative;
  overflow: visible;
  width: 100%; /* 占据 grid 的全部宽度 */
  max-width: 500px; /* 限制最大宽度 */
}

.paper-preview-header {
  position: relative;
  padding: 2px 0 10px;
  margin-bottom: 10px;
  border-bottom: 2px solid rgba(0, 0, 0, 0.14);
}

.preview-h1 {
  font-weight: 900;
  font-size: 15px;
  letter-spacing: 0.3px;
  margin-bottom: 2px;
  color: rgba(0, 0, 0, 0.85);
  line-height: 1.4;
  word-wrap: break-word; /* 允许长文本换行 */
  overflow-wrap: break-word; /* 确保长单词也能换行 */
}

.preview-h2 {
  font-size: 11px;
  color: rgba(0, 0, 0, 0.60);
  margin-bottom: 8px;
  line-height: 1.4;
}

.preview-fields {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 8px 12px;
  font-size: 11px;
  color: rgba(0, 0, 0, 0.70);
}

.preview-field {
  display: flex;
  align-items: flex-end;
  gap: 6px;
  position: relative;
  min-width: 0; /* 允许 flex 子元素缩小 */
}

.preview-field span {
  flex: 0 0 auto;
  min-width: 40px;
}

.preview-line {
  flex: 1;
  height: 14px;
  border-bottom: 1px solid rgba(0, 0, 0, 0.35);
  position: relative;
  min-width: 0; /* 允许 flex 子元素缩小 */
  overflow: visible; /* 允许文字溢出显示 */
}

.preview-handname,
.preview-handmeta {
  position: absolute;
  left: 6px;
  bottom: -4px;
  font-family: "Hannotate SC", "HanziPen SC", "Kaiti SC", "STKaiti", "KaiTi", "Bradley Hand", "Segoe Script", "Snell Roundhand", "Comic Sans MS", cursive;
  letter-spacing: 0.35px;
  white-space: nowrap;
  max-width: calc(100% - 12px);
  overflow: visible; /* 改为 visible，允许文字完整显示 */
  text-overflow: clip; /* 改为 clip，不显示省略号 */
  pointer-events: none;
  text-shadow: 0.6px 0.6px 0 rgba(0, 0, 0, 0.06), -0.4px 0 0 rgba(255, 255, 255, 0.16);
}

.preview-handname {
  font-size: 19px;
  font-weight: 900;
  color: rgba(55, 145, 255, 0.92);
  transform: rotate(-1.2deg);
}

.preview-handmeta {
  font-size: 16px;
  font-weight: 850;
  color: rgba(18, 35, 55, 0.82);
  transform: rotate(-0.8deg);
  opacity: 0.92;
}

.preview-note {
  margin-top: 12px;
  font-size: 12px;
  color: rgba(0, 0, 0, 0.5);
  text-align: center;
  font-style: italic;
}

@media (max-width: 768px) {
  .panel { padding: 16px; }
  .row { flex-direction: column; gap: 16px; }
  
  /* 移动端：预览容器纵向排列 */
  .preview-container {
    flex-direction: column;
    gap: 20px; /* 移动端也保持较大间隙 */
    padding: 0 10px; /* 移动端左右留白 */
    align-items: stretch; /* 移动端卡片占据全部宽度 */
  }
  
  .grid {
    width: 100%;
    max-width: 100%; /* 移动端允许占据全部宽度 */
  }
  
  .card {
    max-width: 100%; /* 移动端允许占据全部宽度 */
  }
  
  .paper-preview {
    padding: 16px;
    max-width: 100%; /* 移动端允许占据全部宽度 */
  }
  
  .preview-h1 {
    font-size: 14px;
  }
  
  .preview-h2 {
    font-size: 10px;
  }
  
  .preview-handmeta {
    font-size: 14px;
  }
  
  .preview-handname {
    font-size: 17px;
  }
}
</style>