import type { ExamDatabase } from '@/types/exam';

// 使用 URL 构造器动态引入图片，确保 Vite 构建后路径正确
// 假设您的图片在 src/assets/images/ 目录下
const getImg = (name: string) => new URL(`../assets/images/${name}`, import.meta.url).href;

// 【新增】音频引入辅助函数
// 假设您的音频在 src/assets/audio/ 目录下
const getAudio = (name: string) => new URL(`../assets/audio/${name}`, import.meta.url).href;

const SVG_IMG_1 = "data:image/svg+xml;utf8," + encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="800" height="420" viewBox="0 0 800 420"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#ffe7a8"/><stop offset="1" stop-color="#ffd0b0"/></linearGradient><filter id="s"><feDropShadow dx="0" dy="12" stdDeviation="14" flood-opacity=".25"/></filter></defs><rect x="0" y="0" width="800" height="420" fill="url(#g)"/><g filter="url(#s)"><rect x="110" y="90" width="580" height="240" rx="26" fill="rgba(255,255,255,.82)" stroke="rgba(0,0,0,.10)"/></g><g opacity=".85"><path d="M140 260 C220 170, 320 240, 400 170 C480 100, 560 170, 660 120" fill="none" stroke="rgba(20,30,40,.55)" stroke-width="12" stroke-linecap="round"/><circle cx="210" cy="180" r="10" fill="rgba(20,30,40,.45)"/><circle cx="570" cy="170" r="10" fill="rgba(20,30,40,.45)"/></g><text x="400" y="228" text-anchor="middle" font-size="66" font-family="system-ui, -apple-system, Segoe UI" font-weight="900" fill="rgba(20,30,40,.68)">SOS</text><text x="400" y="288" text-anchor="middle" font-size="22" font-family="system-ui, -apple-system, Segoe UI" font-weight="800" fill="rgba(20,30,40,.55)">团徽贴纸（示意）</text></svg>`);
const SVG_IMG_2 = "data:image/svg+xml;utf8," + encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="800" height="520" viewBox="0 0 800 520"><defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#d7f1ff"/><stop offset="1" stop-color="#f7e6ff"/></linearGradient><filter id="shadow"><feDropShadow dx="0" dy="10" stdDeviation="12" flood-opacity=".22"/></filter></defs><rect width="800" height="520" fill="url(#bg)"/><g filter="url(#shadow)"><path d="M140 380 C220 260, 320 220, 400 210 C510 198, 590 250, 660 320 L660 430 L140 430 Z" fill="rgba(255,255,255,.82)" stroke="rgba(0,0,0,.10)" stroke-width="2" />
<path d="M160 390 C240 290, 330 255, 400 245 C500 232, 565 275, 640 340" fill="none" stroke="rgba(30,60,90,.60)" stroke-width="10" stroke-linecap="round"/><path d="M185 420 L615 420" stroke="rgba(30,60,90,.25)" stroke-width="4" stroke-linecap="round"/></g><text x="400" y="120" text-anchor="middle" font-size="28" font-family="system-ui, -apple-system, Segoe UI" font-weight="900" fill="rgba(30,60,90,.70)">“纸张折痕与路标”示意图</text><text x="400" y="160" text-anchor="middle" font-size="16" font-family="system-ui, -apple-system, Segoe UI" font-weight="700" fill="rgba(30,60,90,.55)">（用于题目插图演示）</text></svg>`);
const SVG_IMG_3 = "data:image/svg+xml;utf8," + encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="800" height="420" viewBox="0 0 800 420"><rect width="800" height="420" fill="#f0f0f0"/><text x="400" y="210" text-anchor="middle" font-size="30" fill="#999">Live演出场景示意</text></svg>`);

export const EXAM_DB: ExamDatabase = {
  id: 'exam-haruhi-001',

  config: {
    title: '凉宫春日大考试！',
    paperTitle: 'SOS团入团资格认证统一考试',
    paperSubtitle: 'SOS团第15532次期末考试',
    paperMeta: '绝密 ★ 启用前（双面｜四栏｜满分100）',

    exportHeaderTitle: '【成绩单】SOS团入团资格认证统一考试',
    exportHeaderSub: '—— 凉宫春日应援团 · 让世界变得更加热闹的考试委员会 ——',
    exportFooterText: 'Generated by Haruyuki.cn',
    exportOrgName: '凉宫春日应援团 · 让世界变得更加热闹的考试委员会',

    qrCodeText: '扫码挑战',
    qrCodeImg: getImg('https___haruyuki.cn_exam_.png')
  },

  levels: [
    {
      id: 'taniguchi', min: 0, max: 20, name: '谷口级', color: '#795548',
      img: getImg('taniguchi-profile1.webp'), sketch: getImg('taniguchi.webp'),
      comment: 'WAWAWA～你是不是把脑子忘在家里了？'
    },
    {
      id: 'president', min: 21, max: 30, name: '电研社社长级', color: '#558b2f',
      img: getImg('president-profile.webp'), sketch: getImg('president.webp'),
      comment: '喂，这个分数，难道是玩射手座之日上瘾导致的？看来电研社需要转向学习软件的开发了。'
    },
    {
      id: 'imouto', min: 31, max: 40, name: '虚妹级', color: '#ff8a65',
      img: getImg('imouto-profile.webp'), sketch: getImg('imouto.webp'),
      comment: '阿虚～阿虚～这个分数是不是有点太孩子气了？如果不加油的话，就比三味线还笨了哦！'
    },
    {
      id: 'kimidori', min: 41, max: 50, name: '喜绿学姐级', color: '#aed581',
      img: getImg('kimidori-profile.webp'), sketch: getImg('kimidori.webp'),
      comment: '我是来传达学生会的意向的。这个成绩……稍微有点让人担心呢，请多加小心。'
    },
    {
      id: 'asakura', min: 51, max: 59, name: '朝仓凉子级', color: '#009688',
      img: getImg('asakura-profile.webp'), sketch: getImg('asakura.webp'),
      comment: '哎呀，真是遗憾。明明只差一点点就能及格了呢。不过没关系，刀剑可是越是磨砺才越锋利哦。'
    },
    {
      id: 'kyon', min: 60, max: 60, name: '阿虚级', color: '#546e7a',
      img: getImg('kyon-profile.webp'), sketch: getImg('kyon.webp'),
      comment: '哎呀哎呀，刚好及格吗？这就是所谓的“普通”的极致吧。不过在这个异常的世界里，保持这种精准的普通也是一种才能啊。'
    },
    {
      id: 'mikuru', min: 61, max: 65, name: '实玖瑠级', color: '#f48fb1',
      img: getImg('mikuru-profile.webp'), sketch: getImg('mikuru.webp'),
      comment: '呜……那个……虽然分数不是很高，但是及格了真是太好了！请、请喝茶！'
    },
    {
      id: 'tsuruya', min: 66, max: 70, name: '鹤屋学姐级', color: '#fbc02d',
      img: getImg('tsuruya-profile.webp'), sketch: getImg('tsuruya.webp'),
      comment: 'Nyoro~n！很有精神的成绩嘛！虽然不是顶尖，但这份活力我收到了！下次要向着更高分冲刺哦！'
    },
    {
      id: 'itsuki', min: 71, max: 80, name: '古泉一树级', color: '#ef5350',
      img: getImg('itsuki-profile.webp'), sketch: getImg('itsuki.webp'),
      comment: '嗯，非常优秀的表现。这种游刃有余的发挥，确实很有“机关”成员的潜质。凉宫同学应该也会满意的。'
    },
    {
      id: 'nagato', min: 81, max: 90, name: '长门有希级', color: '#7e57c2',
      img: getImg('nagato-profile.webp'), sketch: getImg('nagato.webp'),
      comment: '资讯解析完毕。结果：优秀。知识储备量符合预期推荐值。'
    },
    {
      id: 'haruhi', min: 91, max: 150, name: '凉宫春日级', color: '#ffb300',
      img: getImg('haruhi-profile.webp'), sketch: getImg('haruhi.webp'),
      comment: '太棒了！这才是我们要找的人才！不仅仅是合格，简直是完美！SOS团副团长的位置说不定可以考虑给你哦！'
    }
  ],

  questions: [
    // --- Column 1 ---
    {
      id: 'c1_1', no: 1, column: 'C1', type: 'choice', typeLabel: '单选', score: 2,
      stemBlocks: [{ type: 'text', text: '在《凉宫春日的叹息》中，凉宫春日拍电影时希望有什么动物出现？' }],
      options: [
        { key: 'A', text: '鸽子，黑猫' }, { key: 'B', text: '白猫，野兔' },
        { key: 'C', text: '黑狗，萤火虫' }, { key: 'D', text: '白猫，赤兔' }
      ],
      answer: 'A', analysisBlocks: [{ type: 'text', text: '正确答案是 A。' }]
    },
    {
      id: 'c1_2', no: 2, column: 'C1', type: 'choice', typeLabel: '单选', score: 4,
      stemBlocks: [{ type: 'text', text: '在《凉宫春日的直观》一书中，新年参拜之济，阿虚与外表和美少女别无一二的春日发生了什么令人羡慕的事？' }],
      options: [
        { key: 'A', text: '公主抱' }, { key: 'B', text: '膝枕' },
        { key: 'C', text: '亲吻' }, { key: 'D', text: '背背' }
      ],
      answer: 'D', analysisBlocks: [{ type: 'text', text: '正确答案是 D。' }]
    },
    {
      id: 'c1_3', no: 3, column: 'C1', type: 'fill', typeLabel: '填空', score: 2,
      stemBlocks: [{ type: 'text', text: '在动画《凉宫春日的忧郁》中，“漫无止境的八月”从第12集开始，到第______集结束。（请填写阿拉伯数字）' }],
      answer: '19', analysisBlocks: [{ type: 'text', text: '正确答案是 19。' }]
    },
    {
      id: 'c1_4', no: 4, column: 'C1', type: 'choice', typeLabel: '单选', score: 4,
      stemBlocks: [{ type: 'text', text: '古泉一树在凉宫春日动画系列中说过几次“真羡慕你啊”？' }],
      options: [
        { key: 'A', text: '1次' }, { key: 'B', text: '2次' },
        { key: 'C', text: '3次' }, { key: 'D', text: '4次' }
      ],
      answer: 'C', analysisBlocks: [{ type: 'text', text: '正确答案是 C。' }]
    },
    {
      id: 'c1_5', no: 5, column: 'C1', type: 'choice', typeLabel: '单选', score: 2,
      stemBlocks: [{ type: 'text', text: '动画中凉宫春日的眼瞳是什么颜色的？' }],
      options: [
        { key: 'A', text: '红白色' }, { key: 'B', text: '棕橘色' },
        { key: 'C', text: '赤黑色' }, { key: 'D', text: '紫红色' }
      ],
      answer: 'B', analysisBlocks: [{ type: 'text', text: '正确答案是 B。' }]
    },
    {
      id: 'c1_6', no: 6, column: 'C1', type: 'fill', typeLabel: '填空', score: 4,
      stemBlocks: [{ type: 'text', text: '请填写长门有希住址的门牌号：光阳园西山町1-______。' }],
      answer: '56', analysisBlocks: [{ type: 'text', text: '正确答案是 56。' }]
    },
    {
      id: 'c1_7', no: 7, column: 'C1', type: 'choice', typeLabel: '单选', score: 2,
      stemBlocks: [{ type: 'text', text: '凉宫一众人从哪本书开始进入高二？' }],
      options: [
        { key: 'A', text: '凉宫春日的阴谋' }, { key: 'B', text: '凉宫春日的愤慨' },
        { key: 'C', text: '凉宫春日的分裂' }, { key: 'D', text: '凉宫春日的惊愕' }
      ],
      answer: 'C', analysisBlocks: [{ type: 'text', text: '正确答案是 C。' }]
    },
    {
      id: 'c1_8', no: 8, column: 'C1', type: 'choice', typeLabel: '单选', score: 4,
      stemBlocks: [{ type: 'text', text: '在09动画中，阿虚从哪一集开始称呼凉宫春日为“春日”？' }],
      options: [
        { key: 'A', text: '忧郁Ⅰ' }, { key: 'B', text: '忧郁ⅠⅠ' },
        { key: 'C', text: '忧郁ⅠⅠⅠ' }, { key: 'D', text: '忧郁ⅤⅠ' }
      ],
      answer: 'D', analysisBlocks: [{ type: 'text', text: '正确答案是 D。' }]
    },
    {
      id: 'c1_9', no: 9, column: 'C1', type: 'fill', typeLabel: '填空', score: 2,
      stemBlocks: [{ type: 'text', text: '小说中，朝比奈学姐用来穿越时空的装置英文缩写是______。' }],
      answer: 'TPDD', analysisBlocks: [{ type: 'text', text: '正确答案是 TPDD。' }]
    },

    // --- Column 2 ---
    {
      id: 'c2_1', no: 10, column: 'C2', type: 'choice', typeLabel: '图片单选', score: 4,
      stemBlocks: [
        { type: 'text', text: '观察下图，该画面出现在哪部作品的哪一幕？' },
        { type: 'image', image: { src: getImg('q_img_1.webp'), alt: '舞台演出', title: '场景题1' } }
      ],
      options: [
        { key: 'A', text: '轻音少女第二季毕业演出' }, { key: 'B', text: '孤独摇滚首次Live' },
        { key: 'C', text: '轻音少女第一次学院祭' }, { key: 'D', text: '以上都不是' }
      ],
      answer: 'D', analysisBlocks: [{ type: 'text', text: '正确答案是 D。' }]
    },
    {
      id: 'c2_2', no: 11, column: 'C2', type: 'choice', typeLabel: '音频单选', score: 4,
      stemBlocks: [
        { type: 'text', text: '聆听音频，选择正确的歌名：' },
        // 替换为真实音频路径
        { type: 'audio', audio: { src: getAudio('audio_1.mp3'), title: '神秘音频片段 A', durationText: '0:15' } }
      ],
      options: [
        { key: 'A', text: '拿去吧！水手服' }, { key: 'B', text: 'Super Drive' },
        { key: 'C', text: '春日影' }, { key: 'D', text: 'Lost my music' }
      ],
      answer: 'D', analysisBlocks: [{ type: 'text', text: '正确答案是 D。' }]
    },
    {
      id: 'c2_3', no: 12, column: 'C2', type: 'choice', typeLabel: '音频单选', score: 4,
      stemBlocks: [
        { type: 'text', text: '聆听音频，选择正确的歌名：' },
        { type: 'audio', audio: { src: getAudio('audio_3.mp3'), title: '神秘音频片段 B', durationText: '0:15' } }
      ],
      options: [
        { key: 'A', text: '晴天好心情' }, { key: 'B', text: 'さよならのこと' },
        { key: 'C', text: 'God knows...' }, { key: 'D', text: 'みちしるべ' }
      ],
      answer: 'C', analysisBlocks: [{ type: 'text', text: '正确答案是 C。' }]
    },
    {
      id: 'c2_4', no: 13, column: 'C2', type: 'choice', typeLabel: '单选', score: 4,
      stemBlocks: [{ type: 'text', text: '在动画中，凉宫春日为拍摄电影拿到的摄影机的品牌是？' }],
      options: [
        { key: 'A', text: 'Canon' }, { key: 'B', text: '徐州老味菜' },
        { key: 'C', text: 'Sony' }, { key: 'D', text: 'Fujifilm' }
      ],
      answer: 'C', analysisBlocks: [{ type: 'text', text: '正确答案是 C。' }]
    },
    {
      id: 'c2_5', no: 14, column: 'C2', type: 'choice', typeLabel: '单选', score: 2,
      stemBlocks: [{ type: 'text', text: '凉宫春日从哪家店借来了拍摄电影用的器材？' }],
      options: [
        { key: 'A', text: 'Sony西山町店' }, { key: 'B', text: '通用电气' },
        { key: 'C', text: '山本电器' }, { key: 'D', text: '大森电器' }
      ],
      answer: 'D', analysisBlocks: [{ type: 'text', text: '正确答案是 D。' }]
    },
    {
      id: 'c2_6', no: 15, column: 'C2', type: 'choice', typeLabel: '音频单选', score: 4,
      stemBlocks: [
        { type: 'text', text: '聆听音频，选择正确的歌名：' },
        { type: 'audio', audio: { src: getAudio('audio_4.mp3'), title: '神秘音频片段 C', durationText: '0:15' } }
      ],
      options: [
        { key: 'A', text: 'Go! Go! Maniac!' }, { key: 'B', text: 'U&I' },
        { key: 'C', text: 'ふわふわ时间' }, { key: 'D', text: "Don't say lazy" }
      ],
      answer: 'C', analysisBlocks: [{ type: 'text', text: '正确答案是 C。' }]
    },
    {
      id: 'c2_7', no: 16, column: 'C2', type: 'fill', typeLabel: '填空', score: 2,
      stemBlocks: [{ type: 'text', text: '平野绫在《幸运星》中为哪位角色配音？（请填写全名）' }],
      answer: '泉此方', analysisBlocks: [{ type: 'text', text: '正确答案是 泉此方。' }]
    },

    // --- Column 3 ---
    {
      id: 'c3_1', no: 17, column: 'C3', type: 'choice', typeLabel: '图片单选', score: 4,
      stemBlocks: [
        { type: 'text', text: '下图出自凉宫春日系列哪一话？' },
        { type: 'image', image: { src: getImg('q_img_2.webp'), alt: '消失场景', title: '场景题2' } }
      ],
      options: [
        { key: 'A', text: '09版第2话' }, { key: 'B', text: '09版第11话' },
        { key: 'C', text: '09版第22话' }, { key: 'D', text: '凉宫春日的消失' }
      ],
      answer: 'D', analysisBlocks: [{ type: 'text', text: '正确答案是 D。' }]
    },
    {
      id: 'c3_2', no: 18, column: 'C3', type: 'choice', typeLabel: '单选', score: 2,
      stemBlocks: [{ type: 'text', text: '在小说《凉宫春日的暴走》中，漫无止境的八月一共持续了多少次？' }],
      options: [
        { key: 'A', text: '15532' }, { key: 'B', text: '15498' },
        { key: 'C', text: '11451' }, { key: 'D', text: '15598' }
      ],
      answer: 'B', analysisBlocks: [{ type: 'text', text: '正确答案是 B。' }]
    },
    {
      id: 'c3_3', no: 19, column: 'C3', type: 'choice', typeLabel: '单选', score: 2,
      stemBlocks: [{ type: 'text', text: '在动画《凉宫春日的忧郁》中，漫无止境的八月一共持续了多少次？' }],
      options: [
        { key: 'A', text: '15532' }, { key: 'B', text: '15498' },
        { key: 'C', text: '11451' }, { key: 'D', text: '15598' }
      ],
      answer: 'A', analysisBlocks: [{ type: 'text', text: '正确答案是 A。' }]
    },
    {
      id: 'c3_4', no: 20, column: 'C3', type: 'choice', typeLabel: '音频单选', score: 4,
      stemBlocks: [
        { type: 'text', text: '聆听音频，选择正确的歌名：' },
        { type: 'audio', audio: { src: getAudio('audio_5.mp3'), title: '神秘音频片段 D', durationText: '0:15' } }
      ],
      options: [
        { key: 'A', text: '拿去吧！水手服' }, { key: 'B', text: 'ゆるゆりんりんりんりんりん' },
        { key: 'C', text: 'Sparkling Daydream' }, { key: 'D', text: 'みちしるべ' }
      ],
      answer: 'A', analysisBlocks: [{ type: 'text', text: '正确答案是 A。' }]
    },
    {
      id: 'c3_5', no: 21, column: 'C3', type: 'fill', typeLabel: '填空', score: 2,
      stemBlocks: [{ type: 'text', text: '星期三凉宫春日应该扎了______根辫子。' }],
      answer: '2', analysisBlocks: [{ type: 'text', text: '正确答案是 2。' }]
    },
    {
      id: 'c3_6', no: 22, column: 'C3', type: 'choice', typeLabel: '音频单选', score: 4,
      stemBlocks: [
        { type: 'text', text: '聆听音频，选择正确的歌名：' },
        { type: 'audio', audio: { src: getAudio('audio_8.mp3'), title: '神秘音频片段 E', durationText: '0:15' } }
      ],
      options: [
        { key: 'A', text: 'Go! Go! Maniac!' }, { key: 'B', text: '转动命运之轮' },
        { key: 'C', text: '春日影' }, { key: 'D', text: '以上都不是' }
      ],
      answer: 'C', analysisBlocks: [{ type: 'text', text: '正确答案是 C。' }]
    },
    {
      id: 'c3_7', no: 23, column: 'C3', type: 'choice', typeLabel: '单选', score: 2,
      stemBlocks: [{ type: 'text', text: '前SOS团时期的团长凉宫春日每周二的发型是？' }],
      options: [
        { key: 'A', text: '单马尾' }, { key: 'B', text: '双马尾' },
        { key: 'C', text: '三马尾' }, { key: 'D', text: '散发' }
      ],
      answer: 'A', analysisBlocks: [{ type: 'text', text: '正确答案是 A。' }]
    },
    {
      id: 'c3_8', no: 24, column: 'C3', type: 'fill', typeLabel: '填空', score: 2,
      stemBlocks: [{ type: 'text', text: '京都动画制作过的唯一一部机甲战斗动画是《______》。' }],
      answer: '全金属狂潮', analysisBlocks: [{ type: 'text', text: '即《全金属狂潮校园篇》。' }]
    },

    // --- Column 4 ---
    {
      id: 'c4_1', no: 25, column: 'C4', type: 'choice', typeLabel: '图片单选', score: 4,
      stemBlocks: [
        { type: 'text', text: '下图出现在哪部作品的哪幕画面？' },
        { type: 'image', image: { src: getImg('q_img_3.webp'), alt: 'Live演出', title: '场景题3' } }
      ],
      options: [
        { key: 'A', text: '凉宫09版学院祭演出' }, { key: 'B', text: '轻音少女第一季学院祭' },
        { key: 'C', text: '幸运星主角舞台演出' }, { key: 'D', text: '以上都不是' }
      ],
      answer: 'B', analysisBlocks: [{ type: 'text', text: '正确答案是 B。' }]
    },
    {
      id: 'c4_2', no: 26, column: 'C4', type: 'choice', typeLabel: '音频单选', score: 4,
      stemBlocks: [
        { type: 'text', text: '聆听音频，选择正确的歌名：' },
        { type: 'audio', audio: { src: getAudio('audio_9.mp3'), title: '神秘音频片段 F', durationText: '0:15' } }
      ],
      options: [
        { key: 'A', text: 'Sparkling Daydream' }, { key: 'B', text: '转动命运之轮' },
        { key: 'C', text: '青春Complex' }, { key: 'D', text: '以上都不是' }
      ],
      answer: 'A', analysisBlocks: [{ type: 'text', text: '《中二病也要谈恋爱！》OP。' }]
    },
    {
      id: 'c4_3', no: 27, column: 'C4', type: 'fill', typeLabel: '填空', score: 2,
      stemBlocks: [{ type: 'text', text: '在动画中，谷口说凉宫春日与别人交往时间最短是______分钟。（请填写阿拉伯数字）' }],
      answer: '5', analysisBlocks: [{ type: 'text', text: '正确答案是 5。' }]
    },
    {
      id: 'c4_4', no: 28, column: 'C4', type: 'choice', typeLabel: '单选', score: 2,
      stemBlocks: [{ type: 'text', text: '在动画漫无止境的八月Ⅰ中，阿虚与谁同骑一辆自行车前往游泳馆？' }],
      options: [
        { key: 'A', text: '凉宫春日' }, { key: 'B', text: '长门有希' },
        { key: 'C', text: '朝比奈' }, { key: 'D', text: '凉宫春日,长门有希' }
      ],
      answer: 'D', analysisBlocks: [{ type: 'text', text: '正确答案是 D。' }]
    },
    {
      id: 'c4_5', no: 29, column: 'C4', type: 'choice', typeLabel: '音频单选', score: 4,
      stemBlocks: [
        { type: 'text', text: '聆听音频，选择正确的歌名：' },
        { type: 'audio', audio: { src: getAudio('audio_10.mp3'), title: '神秘音频片段 G', durationText: '0:15' } }
      ],
      options: [
        { key: 'A', text: 'Go! Go! Maniac!' }, { key: 'B', text: '转动命运之轮' },
        { key: 'C', text: '青春Complex' }, { key: 'D', text: 'みちしるべ' }
      ],
      answer: 'D', analysisBlocks: [{ type: 'text', text: '正确答案是 D。' }]
    },
    {
      id: 'c4_6', no: 30, column: 'C4', type: 'fill', typeLabel: '填空', score: 2,
      stemBlocks: [{ type: 'text', text: '凉宫春日应援团成立于______年。（请填写年份数字）' }],
      answer: '2018', analysisBlocks: [{ type: 'text', text: '成立于2018年4月7日。' }]
    },
    {
      id: 'c4_7', no: 31, column: 'C4', type: 'fill', typeLabel: '填空', score: 2,
      stemBlocks: [{ type: 'text', text: '凉宫春日应援团加热部运营的公众号名称为______。' }],
      answer: '春日繁星', analysisBlocks: [{ type: 'text', text: '正确答案是 春日繁星。' }]
    },
    {
      id: 'c4_8', no: 32, column: 'C4', type: 'choice', typeLabel: '单选', score: 2,
      stemBlocks: [{ type: 'text', text: '在凉宫09版动画最后一话中，阿虚与春日一起打着谁的伞回家？' }],
      options: [
        { key: 'A', text: '长门有希' }, { key: 'B', text: '同班同学' },
        { key: 'C', text: '古泉' }, { key: 'D', text: '教师用伞' }
      ],
      answer: 'D', analysisBlocks: [{ type: 'text', text: '正确答案是 D。' }]
    },
    {
      id: 'c4_9', no: 33, column: 'C4', type: 'choice', typeLabel: '音频单选', score: 4,
      stemBlocks: [
        { type: 'text', text: '聆听音频，选择正确的歌名：' },
        { type: 'audio', audio: { src: getAudio('audio_6.mp3'), title: '神秘音频片段 H', durationText: '0:15' } }
      ],
      options: [
        { key: 'A', text: 'Go! Go! Maniac!' }, { key: 'B', text: 'U&I' },
        { key: 'C', text: 'oh my love' }, { key: 'D', text: "Don't say lazy" }
      ],
      answer: 'B', analysisBlocks: [{ type: 'text', text: '正确答案是 B。' }]
    },
    {
      id: 'c4_10', no: 34, column: 'C4', type: 'fill', typeLabel: '填空', score: 2,
      stemBlocks: [{ type: 'text', text: '《轻音少女》中的左手贝斯手名字是______。' }],
      answer: '秋山澪', analysisBlocks: [{ type: 'text', text: '正确答案是 秋山澪。' }]
    }
  ]
};